all:
	g++ socks_server.cpp -o socks_server -std=c++17 -Wall -pedantic -lpthread -lboost_system
	g++ console.cpp -o hw4.cgi -std=c++17 -Wall -pedantic -lpthread -lboost_system
clean:
	rm socks_server
	rm hw4.cgi
